# Generated by Django 5.0 on 2024-05-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10, null=True, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=10, null=True, verbose_name='Prénom')),
                ('mail', models.EmailField(max_length=254)),
                ('tel', models.PositiveIntegerField(null=True, verbose_name='Téléphone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image Profile')),
                ('dateAdhesion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EntreVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateField(blank=True, null=True)),
                ('raison', models.TextField()),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Entrée Vehicule',
            },
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('desc', models.TextField()),
                ('cout', models.PositiveIntegerField(null=True, verbose_name='Coût')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('ref', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image Piece')),
                ('desc', models.TextField()),
                ('prix', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(choices=[('MECANIQUE', 'MECANIQUE'), ('TOLERIE', 'TOLERIE'), ('ELECTRONIQUE', 'ELECTRONIQUE'), ('CLIMATISATION', 'CLIMATISATION'), ('HABITACLE', 'HABITACLE')], max_length=13, null=True, verbose_name='Spécialité')),
                ('nom', models.CharField(max_length=50, null=True, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=50, null=True, verbose_name='Prénom')),
                ('mail', models.EmailField(max_length=254)),
                ('tel', models.PositiveIntegerField(null=True, verbose_name='Téléphone')),
                ('salaire', models.PositiveIntegerField(null=True, verbose_name='salaire')),
                ('date_arrive', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image Profile')),
            ],
        ),
        migrations.CreateModel(
            name='EntrePanne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolu', models.BooleanField(default=False)),
                ('entre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarManagement.entrevehicule')),
                ('panne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarManagement.panne')),
            ],
        ),
        migrations.AddField(
            model_name='entrevehicule',
            name='pannes',
            field=models.ManyToManyField(blank=True, through='CarManagement.EntrePanne', to='CarManagement.panne'),
        ),
        migrations.CreateModel(
            name='QuantitePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('panne', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CarManagement.panne')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CarManagement.piece')),
            ],
        ),
        migrations.AddField(
            model_name='panne',
            name='piece',
            field=models.ManyToManyField(through='CarManagement.QuantitePiece', to='CarManagement.piece'),
        ),
        migrations.CreateModel(
            name='SortieVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateField(blank=True, null=True)),
                ('cout', models.PositiveIntegerField(blank=True, verbose_name='Coût')),
                ('entre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CarManagement.entrevehicule')),
            ],
            options={
                'verbose_name': 'Sortie Vehicule',
            },
        ),
        migrations.AddField(
            model_name='entrevehicule',
            name='techniciens',
            field=models.ManyToManyField(blank=True, to='CarManagement.technicien'),
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carburant', models.CharField(choices=[('Essence', 'Essence'), ('Diesel', 'Diesel')], max_length=7, null=True, verbose_name='Carburant')),
                ('libelle', models.CharField(max_length=50, null=True, verbose_name='Libellé')),
                ('immatriculation', models.CharField(max_length=15, null=True, unique=True, verbose_name='Immatriculation')),
                ('couleur', models.CharField(max_length=10, null=True, verbose_name='Couleur')),
                ('poids', models.PositiveIntegerField(null=True, verbose_name='Poids')),
                ('date_arrive', models.DateField(null=True)),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CarManagement.client')),
            ],
        ),
        migrations.AddField(
            model_name='entrevehicule',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CarManagement.vehicule'),
        ),
    ]
